import { BiSLists } from './types.js';

export const BASELINE_BIS: BiSLists = {
  WARRIOR: {
    Fury: {
      phase: 1,
      slots: {
        HEAD: { itemId: 12640, name: 'Lionheart Helm', source: 'Blacksmithing (300)' },
        NECK: { itemId: 18404, name: 'Onyxia Tooth Pendant', source: "Onyxia's Lair - Head of Onyxia" },
        SHOULDERS: { itemId: 13405, name: 'Truestrike Shoulders', source: 'Upper Blackrock Spire - Pyroguard Emberseer' },
        BACK: { itemId: 13340, name: 'Cape of the Black Baron', source: 'Stratholme - Baron Rivendare' },
        CHEST: { itemId: 11726, name: 'Savage Gladiator Chain', source: 'Blackrock Depths - Gorosh the Dervish' },
        WRISTS: { itemId: 19146, name: 'Wristguards of Stability', source: 'Molten Core - Garr / Shazzrah' },
        HANDS: { itemId: 14551, name: "Edgemaster's Handguards", source: 'World Drop (Azeroth)' },
        WAIST: { itemId: 19137, name: 'Onslaught Girdle', source: 'Molten Core - Ragnaros' },
        LEGS: { itemId: 14554, name: 'Cloudkeeper Legplates', source: 'World Drop (Azeroth)' },
        FEET: { itemId: 14616, name: 'Bloodmail Boots', source: 'Scholomance - Bosses' },
        FINGER_1: { itemId: 17063, name: 'Band of Accuria', source: 'Molten Core - Ragnaros' },
        FINGER_2: { itemId: 18821, name: 'Quick Strike Ring', source: 'Molten Core - Bosses' },
        TRINKET_1: { itemId: 11815, name: 'Hand of Justice', source: 'Blackrock Depths - Emperor Dagran Thaurissan' },
        TRINKET_2: { itemId: 13965, name: "Blackhand's Breadth", source: 'Upper Blackrock Spire Quest - For The Horde / General Drakkisath' },
        MAIN_HAND: { itemId: 17075, name: "Vis'kag the Bloodletter", source: "Onyxia's Lair - Onyxia" },
        OFF_HAND: { itemId: 18832, name: 'Brutality Blade', source: 'Molten Core - Garr' },
        RANGED: { itemId: 17069, name: "Striker's Mark", source: 'Molten Core - Magmadar' },
      },
    },
    Protection: {
      phase: 1,
      slots: {
        HEAD: { itemId: 16866, name: 'Helm of Might', source: 'Molten Core - Magmadar' },
        NECK: { itemId: 17064, name: 'Medallion of Steadfast Might', source: 'Molten Core - Magmadar' },
        SHOULDERS: { itemId: 16868, name: 'Pauldrons of Might', source: 'Molten Core - Sulfuron Harbinger' },
        BACK: { itemId: 19084, name: 'Dragon\'s Blood Cape', source: 'Molten Core - Ragnaros' },
        CHEST: { itemId: 16865, name: 'Breastplate of Might', source: 'Molten Core - Golemagg' },
        WRISTS: { itemId: 16861, name: 'Bracers of Might', source: 'Molten Core - Trash Mobs' },
        HANDS: { itemId: 16863, name: 'Gauntlets of Might', source: 'Molten Core - Gehennas' },
        WAIST: { itemId: 16864, name: 'Belt of Might', source: 'Molten Core - Trash Mobs' },
        LEGS: { itemId: 16867, name: 'Legplates of Might', source: 'Molten Core - Magmadar' },
        FEET: { itemId: 16862, name: 'Sabatons of Might', source: 'Molten Core - Gehennas' },
        FINGER_1: { itemId: 19147, name: 'Ring of Binding', source: 'Molten Core - Baron Geddon' },
        FINGER_2: { itemId: 17063, name: 'Band of Accuria', source: 'Molten Core - Ragnaros' },
        TRINKET_1: { itemId: 11815, name: 'Hand of Justice', source: 'Blackrock Depths - Emperor Dagran Thaurissan' },
        TRINKET_2: { itemId: 19406, name: 'Drake Fang Talisman', source: 'Blackwing Lair - Ebonroc' },
        MAIN_HAND: { itemId: 17075, name: 'Vis\'kag the Bloodletter', source: 'Onyxia\'s Lair - Onyxia' },
        OFF_HAND: { itemId: 17066, name: 'Drillborer Disk', source: 'Molten Core - Garr' },
        RANGED: { itemId: 17072, name: 'Blastershot Launcher', source: 'Molten Core - Golemagg' },
      },
    },
    Arms: {
      phase: 1,
      slots: {
        HEAD: { itemId: 12640, name: 'Lionheart Helm', source: 'Blacksmithing (300)' },
        NECK: { itemId: 18404, name: 'Onyxia Tooth Pendant', source: "Onyxia's Lair - Head of Onyxia" },
        SHOULDERS: { itemId: 13405, name: 'Truestrike Shoulders', source: 'Upper Blackrock Spire - Pyroguard Emberseer' },
        BACK: { itemId: 13340, name: 'Cape of the Black Baron', source: 'Stratholme - Baron Rivendare' },
        CHEST: { itemId: 11726, name: 'Savage Gladiator Chain', source: 'Blackrock Depths - Gorosh the Dervish' },
        WRISTS: { itemId: 19146, name: 'Wristguards of Stability', source: 'Molten Core - Garr / Shazzrah' },
        HANDS: { itemId: 14551, name: "Edgemaster's Handguards", source: 'World Drop (Azeroth)' },
        WAIST: { itemId: 19137, name: 'Onslaught Girdle', source: 'Molten Core - Ragnaros' },
        LEGS: { itemId: 14554, name: 'Cloudkeeper Legplates', source: 'World Drop (Azeroth)' },
        FEET: { itemId: 14616, name: 'Bloodmail Boots', source: 'Scholomance - Bosses' },
        FINGER_1: { itemId: 17063, name: 'Band of Accuria', source: 'Molten Core - Ragnaros' },
        FINGER_2: { itemId: 18821, name: 'Quick Strike Ring', source: 'Molten Core - Bosses' },
        TRINKET_1: { itemId: 11815, name: 'Hand of Justice', source: 'Blackrock Depths - Emperor Dagran Thaurissan' },
        TRINKET_2: { itemId: 13965, name: "Blackhand's Breadth", source: 'Upper Blackrock Spire Quest - For The Horde' },
        MAIN_HAND: { itemId: 17076, name: "Bonereaver's Edge", source: 'Molten Core - Ragnaros' },
        OFF_HAND: { itemId: 0, name: 'None (2H Weapon)', source: 'N/A' },
        RANGED: { itemId: 17069, name: "Striker's Mark", source: 'Molten Core - Magmadar' },
      },
    },
  },
  PALADIN: {
    Retribution: {
      phase: 1,
      slots: {
        HEAD: { itemId: 12640, name: 'Lionheart Helm', source: 'Blacksmithing (300)' },
        NECK: { itemId: 18404, name: 'Onyxia Tooth Pendant', source: "Onyxia's Lair - Head of Onyxia" },
        SHOULDERS: { itemId: 13405, name: 'Truestrike Shoulders', source: 'Upper Blackrock Spire - Pyroguard Emberseer' },
        BACK: { itemId: 13340, name: 'Cape of the Black Baron', source: 'Stratholme - Baron Rivendare' },
        CHEST: { itemId: 11726, name: 'Savage Gladiator Chain', source: 'Blackrock Depths - Gorosh the Dervish' },
        WRISTS: { itemId: 12936, name: 'Battleborn Armbraces', source: 'Upper Blackrock Spire - Rend Blackhand' },
        HANDS: { itemId: 12548, name: 'Devilsaur Gauntlets', source: 'Leatherworking (250)' },
        WAIST: { itemId: 19137, name: 'Onslaught Girdle', source: 'Molten Core - Ragnaros' },
        LEGS: { itemId: 15062, name: 'Devilsaur Leggings', source: 'Leatherworking (250)' },
        FEET: { itemId: 14616, name: 'Bloodmail Boots', source: 'Scholomance - Bosses' },
        FINGER_1: { itemId: 17713, name: 'Blackstone Ring', source: 'Maraudon - Princess Theradras' },
        FINGER_2: { itemId: 13098, name: 'Painweaver Band', source: 'Upper Blackrock Spire - General Drakkisath' },
        TRINKET_1: { itemId: 11815, name: 'Hand of Justice', source: 'Blackrock Depths - Emperor Dagran Thaurissan' },
        TRINKET_2: { itemId: 13965, name: "Blackhand's Breadth", source: 'Upper Blackrock Spire Quest' },
        MAIN_HAND: { itemId: 17182, name: 'Sulfuras, Hand of Ragnaros', source: 'Molten Core - Ragnaros' },
        OFF_HAND: { itemId: 0, name: 'None (2H Weapon)', source: 'N/A' },
        RANGED: { itemId: 22401, name: 'Libram of Fervor', source: 'World Drop' },
      },
    },
    Holy: {
      phase: 1,
      slots: {
        HEAD: { itemId: 16813, name: 'Lawbringer Helm', source: 'Molten Core - Garr' },
        NECK: { itemId: 17109, name: 'Choker of the Fire Lord', source: 'Molten Core - Ragnaros' },
        SHOULDERS: { itemId: 16817, name: 'Lawbringer Spaulders', source: 'Molten Core - Baron Geddon' },
        BACK: { itemId: 18510, name: 'Hide of the Wild', source: 'Leatherworking (300)' },
        CHEST: { itemId: 16815, name: 'Lawbringer Chestguard', source: 'Molten Core - Golemagg' },
        WRISTS: { itemId: 16819, name: 'Lawbringer Bracers', source: 'Molten Core - Trash Mobs' },
        HANDS: { itemId: 16812, name: 'Lawbringer Gauntlets', source: 'Molten Core - Gehennas' },
        WAIST: { itemId: 16811, name: 'Lawbringer Belt', source: 'Molten Core - Trash Mobs' },
        LEGS: { itemId: 16816, name: 'Lawbringer Legplates', source: 'Molten Core - Magmadar' },
        FEET: { itemId: 16814, name: 'Lawbringer Boots', source: 'Molten Core - Lucifron' },
        FINGER_1: { itemId: 19140, name: 'Cauterizing Band', source: 'Molten Core - Major Domo Executus' },
        FINGER_2: { itemId: 16058, name: 'Fordring\'s Seal', source: 'Quest - In Dreams' },
        TRINKET_1: { itemId: 18469, name: 'Royal Seal of Eldre\'Thalas', source: 'Dire Maul - Book Quest' },
        TRINKET_2: { itemId: 12930, name: 'Briarwood Reed', source: 'Upper Blackrock Spire - Jed Runewatcher' },
        MAIN_HAND: { itemId: 17105, name: 'Aurastone Hammer', source: 'Molten Core - Garr' },
        OFF_HAND: { itemId: 17066, name: 'Drillborer Disk', source: 'Molten Core - Garr' },
        RANGED: { itemId: 23201, name: 'Libram of Hope', source: 'Dire Maul East' },
      },
    },
    Protection: {
      phase: 1,
      slots: {
        HEAD: { itemId: 12640, name: 'Lionheart Helm', source: 'Blacksmithing (300)' },
        NECK: { itemId: 17064, name: 'Medallion of Steadfast Might', source: 'Molten Core - Magmadar' },
        SHOULDERS: { itemId: 16868, name: 'Pauldrons of Might', source: 'Molten Core - Sulfuron' },
        BACK: { itemId: 19084, name: 'Dragon\'s Blood Cape', source: 'Molten Core - Ragnaros' },
        CHEST: { itemId: 11726, name: 'Savage Gladiator Chain', source: 'Blackrock Depths - Gorosh' },
        WRISTS: { itemId: 16861, name: 'Bracers of Might', source: 'Molten Core - Trash Mobs' },
        HANDS: { itemId: 16863, name: 'Gauntlets of Might', source: 'Molten Core - Gehennas' },
        WAIST: { itemId: 19137, name: 'Onslaught Girdle', source: 'Molten Core - Ragnaros' },
        LEGS: { itemId: 16867, name: 'Legplates of Might', source: 'Molten Core - Magmadar' },
        FEET: { itemId: 14616, name: 'Bloodmail Boots', source: 'Scholomance - Bosses' },
        FINGER_1: { itemId: 19147, name: 'Ring of Binding', source: 'Molten Core - Baron Geddon' },
        FINGER_2: { itemId: 17713, name: 'Blackstone Ring', source: 'Maraudon - Princess Theradras' },
        TRINKET_1: { itemId: 11815, name: 'Hand of Justice', source: 'Blackrock Depths - Emperor Dagran Thaurissan' },
        TRINKET_2: { itemId: 13965, name: 'Blackhand\'s Breadth', source: 'Upper Blackrock Spire Quest' },
        MAIN_HAND: { itemId: 17075, name: 'Vis\'kag the Bloodletter', source: 'Onyxia\'s Lair - Onyxia' },
        OFF_HAND: { itemId: 17066, name: 'Drillborer Disk', source: 'Molten Core - Garr' },
        RANGED: { itemId: 23203, name: 'Libram of Truth', source: 'World Drop' },
      },
    },
  },
  HUNTER: {
    'Beast Mastery': {
      phase: 1,
      slots: {
        HEAD: { itemId: 16846, name: 'Giantstalker\'s Helmet', source: 'Molten Core - Garr' },
        NECK: { itemId: 18404, name: 'Onyxia Tooth Pendant', source: "Onyxia's Lair - Head of Onyxia" },
        SHOULDERS: { itemId: 16848, name: 'Giantstalker\'s Epaulets', source: 'Molten Core - Sulfuron Harbinger' },
        BACK: { itemId: 13340, name: 'Cape of the Black Baron', source: 'Stratholme - Baron Rivendare' },
        CHEST: { itemId: 16845, name: 'Giantstalker\'s Breastplate', source: 'Molten Core - Golemagg' },
        WRISTS: { itemId: 16850, name: 'Giantstalker\'s Bracers', source: 'Molten Core - Trash Mobs' },
        HANDS: { itemId: 16849, name: 'Giantstalker\'s Gloves', source: 'Molten Core - Gehennas' },
        WAIST: { itemId: 16851, name: 'Giantstalker\'s Belt', source: 'Molten Core - Trash Mobs' },
        LEGS: { itemId: 16847, name: 'Giantstalker\'s Leggings', source: 'Molten Core - Magmadar' },
        FEET: { itemId: 16844, name: 'Giantstalker\'s Boots', source: 'Molten Core - Lucifron' },
        FINGER_1: { itemId: 19144, name: 'Band of Accuria', source: 'Molten Core - Ragnaros' },
        FINGER_2: { itemId: 17713, name: 'Blackstone Ring', source: 'Maraudon - Princess Theradras' },
        TRINKET_1: { itemId: 18473, name: 'Royal Seal of Eldre\'Thalas', source: 'Dire Maul - Book Quest' },
        TRINKET_2: { itemId: 13965, name: 'Blackhand\'s Breadth', source: 'Upper Blackrock Spire Quest' },
        MAIN_HAND: { itemId: 18725, name: 'Lok\'delar, Stave of the Ancient Keepers', source: 'Hunter Epic Quest - Majordomo' },
        OFF_HAND: { itemId: 0, name: 'None (2H Weapon)', source: 'N/A' },
        RANGED: { itemId: 18713, name: 'Rhok\'delar, Longbow of the Ancient Keepers', source: 'Hunter Epic Quest - Majordomo' },
      },
    },
    Marksmanship: {
      phase: 1,
      slots: {
        HEAD: { itemId: 16846, name: 'Giantstalker\'s Helmet', source: 'Molten Core - Garr' },
        NECK: { itemId: 18404, name: 'Onyxia Tooth Pendant', source: "Onyxia's Lair - Head of Onyxia" },
        SHOULDERS: { itemId: 16848, name: 'Giantstalker\'s Epaulets', source: 'Molten Core - Sulfuron Harbinger' },
        BACK: { itemId: 13340, name: 'Cape of the Black Baron', source: 'Stratholme - Baron Rivendare' },
        CHEST: { itemId: 16845, name: 'Giantstalker\'s Breastplate', source: 'Molten Core - Golemagg' },
        WRISTS: { itemId: 16850, name: 'Giantstalker\'s Bracers', source: 'Molten Core - Trash Mobs' },
        HANDS: { itemId: 16849, name: 'Giantstalker\'s Gloves', source: 'Molten Core - Gehennas' },
        WAIST: { itemId: 16851, name: 'Giantstalker\'s Belt', source: 'Molten Core - Trash Mobs' },
        LEGS: { itemId: 16847, name: 'Giantstalker\'s Leggings', source: 'Molten Core - Magmadar' },
        FEET: { itemId: 16844, name: 'Giantstalker\'s Boots', source: 'Molten Core - Lucifron' },
        FINGER_1: { itemId: 19144, name: 'Band of Accuria', source: 'Molten Core - Ragnaros' },
        FINGER_2: { itemId: 17713, name: 'Blackstone Ring', source: 'Maraudon - Princess Theradras' },
        TRINKET_1: { itemId: 18473, name: 'Royal Seal of Eldre\'Thalas', source: 'Dire Maul - Book Quest' },
        TRINKET_2: { itemId: 13965, name: 'Blackhand\'s Breadth', source: 'Upper Blackrock Spire Quest' },
        MAIN_HAND: { itemId: 18725, name: 'Lok\'delar, Stave of the Ancient Keepers', source: 'Hunter Epic Quest - Majordomo' },
        OFF_HAND: { itemId: 0, name: 'None (2H Weapon)', source: 'N/A' },
        RANGED: { itemId: 18713, name: 'Rhok\'delar, Longbow of the Ancient Keepers', source: 'Hunter Epic Quest - Majordomo' },
      },
    },
    Survival: {
      phase: 1,
      slots: {
        HEAD: { itemId: 16846, name: 'Giantstalker\'s Helmet', source: 'Molten Core - Garr' },
        NECK: { itemId: 18404, name: 'Onyxia Tooth Pendant', source: "Onyxia's Lair - Head of Onyxia" },
        SHOULDERS: { itemId: 13405, name: 'Truestrike Shoulders', source: 'Upper Blackrock Spire - Pyroguard Emberseer' },
        BACK: { itemId: 13340, name: 'Cape of the Black Baron', source: 'Stratholme - Baron Rivendare' },
        CHEST: { itemId: 16845, name: 'Giantstalker\'s Breastplate', source: 'Molten Core - Golemagg' },
        WRISTS: { itemId: 16850, name: 'Giantstalker\'s Bracers', source: 'Molten Core - Trash Mobs' },
        HANDS: { itemId: 16849, name: 'Giantstalker\'s Gloves', source: 'Molten Core - Gehennas' },
        WAIST: { itemId: 16851, name: 'Giantstalker\'s Belt', source: 'Molten Core - Trash Mobs' },
        LEGS: { itemId: 16847, name: 'Giantstalker\'s Leggings', source: 'Molten Core - Magmadar' },
        FEET: { itemId: 16844, name: 'Giantstalker\'s Boots', source: 'Molten Core - Lucifron' },
        FINGER_1: { itemId: 19144, name: 'Band of Accuria', source: 'Molten Core - Ragnaros' },
        FINGER_2: { itemId: 17713, name: 'Blackstone Ring', source: 'Maraudon - Princess Theradras' },
        TRINKET_1: { itemId: 18473, name: 'Royal Seal of Eldre\'Thalas', source: 'Dire Maul - Book Quest' },
        TRINKET_2: { itemId: 13965, name: 'Blackhand\'s Breadth', source: 'Upper Blackrock Spire Quest' },
        MAIN_HAND: { itemId: 18725, name: 'Lok\'delar, Stave of the Ancient Keepers', source: 'Hunter Epic Quest - Majordomo' },
        OFF_HAND: { itemId: 0, name: 'None (2H Weapon)', source: 'N/A' },
        RANGED: { itemId: 18713, name: 'Rhok\'delar, Longbow of the Ancient Keepers', source: 'Hunter Epic Quest - Majordomo' },
      },
    },
  },
  ROGUE: {
    'Combat Swords': {
      phase: 1,
      slots: {
        HEAD: { itemId: 16821, name: 'Nightslayer Cover', source: 'Molten Core - Garr' },
        NECK: { itemId: 18404, name: 'Onyxia Tooth Pendant', source: "Onyxia's Lair - Head of Onyxia" },
        SHOULDERS: { itemId: 16823, name: 'Nightslayer Shoulder Pads', source: 'Molten Core - Sulfuron Harbinger' },
        BACK: { itemId: 13340, name: 'Cape of the Black Baron', source: 'Stratholme - Baron Rivendare' },
        CHEST: { itemId: 16820, name: 'Nightslayer Chestpiece', source: 'Molten Core - Golemagg' },
        WRISTS: { itemId: 16825, name: 'Nightslayer Bracelets', source: 'Molten Core - Trash Mobs' },
        HANDS: { itemId: 16826, name: 'Nightslayer Gloves', source: 'Molten Core - Gehennas' },
        WAIST: { itemId: 16827, name: 'Nightslayer Belt', source: 'Molten Core - Trash Mobs' },
        LEGS: { itemId: 16822, name: 'Nightslayer Pants', source: 'Molten Core - Magmadar' },
        FEET: { itemId: 16824, name: 'Nightslayer Boots', source: 'Molten Core - Lucifron' },
        FINGER_1: { itemId: 19144, name: 'Band of Accuria', source: 'Molten Core - Ragnaros' },
        FINGER_2: { itemId: 17713, name: 'Blackstone Ring', source: 'Maraudon - Princess Theradras' },
        TRINKET_1: { itemId: 11815, name: 'Hand of Justice', source: 'Blackrock Depths - Emperor Dagran Thaurissan' },
        TRINKET_2: { itemId: 13965, name: 'Blackhand\'s Breadth', source: 'Upper Blackrock Spire Quest' },
        MAIN_HAND: { itemId: 17075, name: 'Vis\'kag the Bloodletter', source: 'Onyxia\'s Lair - Onyxia' },
        OFF_HAND: { itemId: 18838, name: 'Brutality Blade', source: 'Molten Core - Garr' },
        RANGED: { itemId: 17072, name: 'Blastershot Launcher', source: 'Molten Core - Golemagg' },
      },
    },
    Assassination: {
      phase: 1,
      slots: {
        HEAD: { itemId: 16821, name: 'Nightslayer Cover', source: 'Molten Core - Garr' },
        NECK: { itemId: 18404, name: 'Onyxia Tooth Pendant', source: "Onyxia's Lair - Head of Onyxia" },
        SHOULDERS: { itemId: 16823, name: 'Nightslayer Shoulder Pads', source: 'Molten Core - Sulfuron Harbinger' },
        BACK: { itemId: 13340, name: 'Cape of the Black Baron', source: 'Stratholme - Baron Rivendare' },
        CHEST: { itemId: 16820, name: 'Nightslayer Chestpiece', source: 'Molten Core - Golemagg' },
        WRISTS: { itemId: 16825, name: 'Nightslayer Bracelets', source: 'Molten Core - Trash Mobs' },
        HANDS: { itemId: 16826, name: 'Nightslayer Gloves', source: 'Molten Core - Gehennas' },
        WAIST: { itemId: 16827, name: 'Nightslayer Belt', source: 'Molten Core - Trash Mobs' },
        LEGS: { itemId: 16822, name: 'Nightslayer Pants', source: 'Molten Core - Magmadar' },
        FEET: { itemId: 16824, name: 'Nightslayer Boots', source: 'Molten Core - Lucifron' },
        FINGER_1: { itemId: 19144, name: 'Band of Accuria', source: 'Molten Core - Ragnaros' },
        FINGER_2: { itemId: 17713, name: 'Blackstone Ring', source: 'Maraudon - Princess Theradras' },
        TRINKET_1: { itemId: 11815, name: 'Hand of Justice', source: 'Blackrock Depths - Emperor Dagran Thaurissan' },
        TRINKET_2: { itemId: 13965, name: 'Blackhand\'s Breadth', source: 'Upper Blackrock Spire Quest' },
        MAIN_HAND: { itemId: 17068, name: 'Deathbringer', source: 'Onyxia\'s Lair - Onyxia' },
        OFF_HAND: { itemId: 18805, name: 'Core Hound Tooth', source: 'Molten Core - Lucifron' },
        RANGED: { itemId: 17072, name: 'Blastershot Launcher', source: 'Molten Core - Golemagg' },
      },
    },
    Subtlety: {
      phase: 1,
      slots: {
        HEAD: { itemId: 16821, name: 'Nightslayer Cover', source: 'Molten Core - Garr' },
        NECK: { itemId: 18404, name: 'Onyxia Tooth Pendant', source: "Onyxia's Lair - Head of Onyxia" },
        SHOULDERS: { itemId: 16823, name: 'Nightslayer Shoulder Pads', source: 'Molten Core - Sulfuron Harbinger' },
        BACK: { itemId: 13340, name: 'Cape of the Black Baron', source: 'Stratholme - Baron Rivendare' },
        CHEST: { itemId: 16820, name: 'Nightslayer Chestpiece', source: 'Molten Core - Golemagg' },
        WRISTS: { itemId: 16825, name: 'Nightslayer Bracelets', source: 'Molten Core - Trash Mobs' },
        HANDS: { itemId: 16826, name: 'Nightslayer Gloves', source: 'Molten Core - Gehennas' },
        WAIST: { itemId: 16827, name: 'Nightslayer Belt', source: 'Molten Core - Trash Mobs' },
        LEGS: { itemId: 16822, name: 'Nightslayer Pants', source: 'Molten Core - Magmadar' },
        FEET: { itemId: 16824, name: 'Nightslayer Boots', source: 'Molten Core - Lucifron' },
        FINGER_1: { itemId: 19144, name: 'Band of Accuria', source: 'Molten Core - Ragnaros' },
        FINGER_2: { itemId: 17713, name: 'Blackstone Ring', source: 'Maraudon - Princess Theradras' },
        TRINKET_1: { itemId: 11815, name: 'Hand of Justice', source: 'Blackrock Depths - Emperor Dagran Thaurissan' },
        TRINKET_2: { itemId: 13965, name: 'Blackhand\'s Breadth', source: 'Upper Blackrock Spire Quest' },
        MAIN_HAND: { itemId: 18838, name: 'Brutality Blade', source: 'Molten Core - Garr' },
        OFF_HAND: { itemId: 18805, name: 'Core Hound Tooth', source: 'Molten Core - Lucifron' },
        RANGED: { itemId: 17072, name: 'Blastershot Launcher', source: 'Molten Core - Golemagg' },
      },
    },
  },
  PRIEST: {
    Holy: {
      phase: 1,
      slots: {
        HEAD: { itemId: 16813, name: 'Circlet of Prophecy', source: 'Molten Core - Garr' },
        NECK: { itemId: 17109, name: 'Choker of the Fire Lord', source: 'Molten Core - Ragnaros' },
        SHOULDERS: { itemId: 16817, name: 'Mantle of Prophecy', source: 'Molten Core - Baron Geddon' },
        BACK: { itemId: 18510, name: 'Hide of the Wild', source: 'Leatherworking (300)' },
        CHEST: { itemId: 13346, name: 'Robes of the Exalted', source: 'Stratholme - Baron Rivendare' },
        WRISTS: { itemId: 16819, name: 'Vambraces of Prophecy', source: 'Molten Core - Trash Mobs' },
        HANDS: { itemId: 16812, name: 'Gloves of Prophecy', source: 'Molten Core - Gehennas' },
        WAIST: { itemId: 16811, name: 'Girdle of Prophecy', source: 'Molten Core - Trash Mobs' },
        LEGS: { itemId: 16815, name: 'Pants of Prophecy', source: 'Molten Core - Magmadar' },
        FEET: { itemId: 16814, name: 'Boots of Prophecy', source: 'Molten Core - Lucifron' },
        FINGER_1: { itemId: 19140, name: 'Cauterizing Band', source: 'Molten Core - Majordomo Executus' },
        FINGER_2: { itemId: 16058, name: 'Fordring\'s Seal', source: 'Quest - In Dreams' },
        TRINKET_1: { itemId: 18469, name: 'Royal Seal of Eldre\'Thalas', source: 'Dire Maul - Book Quest' },
        TRINKET_2: { itemId: 12930, name: 'Briarwood Reed', source: 'Upper Blackrock Spire - Jed Runewatcher' },
        MAIN_HAND: { itemId: 18608, name: 'Benediction', source: 'Priest Epic Quest - Majordomo' },
        OFF_HAND: { itemId: 0, name: 'None (Staff)', source: 'N/A' },
        RANGED: { itemId: 13938, name: 'Bonecreeper Stylus', source: 'Scholomance - Darkmaster Gandling' },
      },
    },
    Shadow: {
      phase: 1,
      slots: {
        HEAD: { itemId: 10504, name: 'Spellweaver\'s Turban', source: 'Upper Blackrock Spire - General Drakkisath' },
        NECK: { itemId: 17109, name: 'Choker of the Fire Lord', source: 'Molten Core - Ragnaros' },
        SHOULDERS: { itemId: 14112, name: 'Felcloth Shoulders', source: 'Tailoring (300)' },
        BACK: { itemId: 18208, name: 'Drape of Benediction', source: 'Dire Maul North' },
        CHEST: { itemId: 14136, name: 'Robes of the Void', source: 'Tailoring (300)' },
        WRISTS: { itemId: 16819, name: 'Vambraces of Prophecy', source: 'Molten Core - Trash Mobs' },
        HANDS: { itemId: 14146, name: 'Felcloth Gloves', source: 'Tailoring (300)' },
        WAIST: { itemId: 19131, name: 'Mana Igniting Cord', source: 'Molten Core - Magmadar' },
        LEGS: { itemId: 14142, name: 'Felcloth Pants', source: 'Tailoring (300)' },
        FEET: { itemId: 14148, name: 'Felcloth Boots', source: 'Tailoring (300)' },
        FINGER_1: { itemId: 19145, name: 'Ring of Spell Power', source: 'Molten Core - Shazzrah' },
        FINGER_2: { itemId: 19145, name: 'Ring of Spell Power', source: 'Molten Core - Lucifron' },
        TRINKET_1: { itemId: 12930, name: 'Briarwood Reed', source: 'Upper Blackrock Spire - Jed Runewatcher' },
        TRINKET_2: { itemId: 18469, name: 'Royal Seal of Eldre\'Thalas', source: 'Dire Maul - Book Quest' },
        MAIN_HAND: { itemId: 18609, name: 'Anathema', source: 'Priest Epic Quest - Majordomo' },
        OFF_HAND: { itemId: 0, name: 'None (Staff)', source: 'N/A' },
        RANGED: { itemId: 13938, name: 'Bonecreeper Stylus', source: 'Scholomance - Darkmaster Gandling' },
      },
    },
    Discipline: {
      phase: 1,
      slots: {
        HEAD: { itemId: 16813, name: 'Circlet of Prophecy', source: 'Molten Core - Garr' },
        NECK: { itemId: 17109, name: 'Choker of the Fire Lord', source: 'Molten Core - Ragnaros' },
        SHOULDERS: { itemId: 16817, name: 'Mantle of Prophecy', source: 'Molten Core - Baron Geddon' },
        BACK: { itemId: 18510, name: 'Hide of the Wild', source: 'Leatherworking (300)' },
        CHEST: { itemId: 13346, name: 'Robes of the Exalted', source: 'Stratholme - Baron Rivendare' },
        WRISTS: { itemId: 16819, name: 'Vambraces of Prophecy', source: 'Molten Core - Trash Mobs' },
        HANDS: { itemId: 16812, name: 'Gloves of Prophecy', source: 'Molten Core - Gehennas' },
        WAIST: { itemId: 16811, name: 'Girdle of Prophecy', source: 'Molten Core - Trash Mobs' },
        LEGS: { itemId: 16815, name: 'Pants of Prophecy', source: 'Molten Core - Magmadar' },
        FEET: { itemId: 16814, name: 'Boots of Prophecy', source: 'Molten Core - Lucifron' },
        FINGER_1: { itemId: 19140, name: 'Cauterizing Band', source: 'Molten Core - Majordomo Executus' },
        FINGER_2: { itemId: 16058, name: 'Fordring\'s Seal', source: 'Quest - In Dreams' },
        TRINKET_1: { itemId: 18469, name: 'Royal Seal of Eldre\'Thalas', source: 'Dire Maul - Book Quest' },
        TRINKET_2: { itemId: 12930, name: 'Briarwood Reed', source: 'Upper Blackrock Spire - Jed Runewatcher' },
        MAIN_HAND: { itemId: 18608, name: 'Benediction', source: 'Priest Epic Quest - Majordomo' },
        OFF_HAND: { itemId: 0, name: 'None (Staff)', source: 'N/A' },
        RANGED: { itemId: 13938, name: 'Bonecreeper Stylus', source: 'Scholomance - Darkmaster Gandling' },
      },
    },
  },
  SHAMAN: {
    Restoration: {
      phase: 1,
      slots: {
        HEAD: { itemId: 16839, name: 'Earthfury Helmet', source: 'Molten Core - Garr' },
        NECK: { itemId: 17109, name: 'Choker of the Fire Lord', source: 'Molten Core - Ragnaros' },
        SHOULDERS: { itemId: 16843, name: 'Earthfury Epaulets', source: 'Molten Core - Baron Geddon' },
        BACK: { itemId: 18510, name: 'Hide of the Wild', source: 'Leatherworking (300)' },
        CHEST: { itemId: 16841, name: 'Earthfury Vestments', source: 'Molten Core - Golemagg' },
        WRISTS: { itemId: 16844, name: 'Earthfury Bracers', source: 'Molten Core - Trash Mobs' },
        HANDS: { itemId: 16840, name: 'Earthfury Gauntlets', source: 'Molten Core - Gehennas' },
        WAIST: { itemId: 16838, name: 'Earthfury Belt', source: 'Molten Core - Trash Mobs' },
        LEGS: { itemId: 16842, name: 'Earthfury Legguards', source: 'Molten Core - Magmadar' },
        FEET: { itemId: 16837, name: 'Earthfury Boots', source: 'Molten Core - Lucifron' },
        FINGER_1: { itemId: 19140, name: 'Cauterizing Band', source: 'Molten Core - Majordomo Executus' },
        FINGER_2: { itemId: 16058, name: 'Fordring\'s Seal', source: 'Quest - In Dreams' },
        TRINKET_1: { itemId: 18471, name: 'Royal Seal of Eldre\'Thalas', source: 'Dire Maul - Book Quest' },
        TRINKET_2: { itemId: 12930, name: 'Briarwood Reed', source: 'Upper Blackrock Spire - Jed Runewatcher' },
        MAIN_HAND: { itemId: 17105, name: 'Aurastone Hammer', source: 'Molten Core - Garr' },
        OFF_HAND: { itemId: 19312, name: 'Malistar\'s Defender', source: 'Molten Core - Shazzrah' },
        RANGED: { itemId: 22396, name: 'Totem of Sustaining', source: 'World Drop' },
      },
    },
    Elemental: {
      phase: 1,
      slots: {
        HEAD: { itemId: 16839, name: 'Earthfury Helmet', source: 'Molten Core - Garr' },
        NECK: { itemId: 17109, name: 'Choker of the Fire Lord', source: 'Molten Core - Ragnaros' },
        SHOULDERS: { itemId: 16843, name: 'Earthfury Epaulets', source: 'Molten Core - Baron Geddon' },
        BACK: { itemId: 18208, name: 'Drape of Benediction', source: 'Dire Maul North' },
        CHEST: { itemId: 16841, name: 'Earthfury Vestments', source: 'Molten Core - Golemagg' },
        WRISTS: { itemId: 16844, name: 'Earthfury Bracers', source: 'Molten Core - Trash Mobs' },
        HANDS: { itemId: 16840, name: 'Earthfury Gauntlets', source: 'Molten Core - Gehennas' },
        WAIST: { itemId: 19131, name: 'Mana Igniting Cord', source: 'Molten Core - Magmadar' },
        LEGS: { itemId: 16842, name: 'Earthfury Legguards', source: 'Molten Core - Magmadar' },
        FEET: { itemId: 16837, name: 'Earthfury Boots', source: 'Molten Core - Lucifron' },
        FINGER_1: { itemId: 19145, name: 'Ring of Spell Power', source: 'Molten Core - Shazzrah' },
        FINGER_2: { itemId: 19145, name: 'Ring of Spell Power', source: 'Molten Core - Lucifron' },
        TRINKET_1: { itemId: 12930, name: 'Briarwood Reed', source: 'Upper Blackrock Spire - Jed Runewatcher' },
        TRINKET_2: { itemId: 18471, name: 'Royal Seal of Eldre\'Thalas', source: 'Dire Maul - Book Quest' },
        MAIN_HAND: { itemId: 17103, name: 'Azuresong Mageblade', source: 'Molten Core - Golemagg' },
        OFF_HAND: { itemId: 19312, name: 'Malistar\'s Defender', source: 'Molten Core - Shazzrah' },
        RANGED: { itemId: 22395, name: 'Totem of the Storm', source: 'World Drop' },
      },
    },
    Enhancement: {
      phase: 1,
      slots: {
        HEAD: { itemId: 12640, name: 'Lionheart Helm', source: 'Blacksmithing (300)' },
        NECK: { itemId: 18404, name: 'Onyxia Tooth Pendant', source: "Onyxia's Lair - Head of Onyxia" },
        SHOULDERS: { itemId: 13405, name: 'Truestrike Shoulders', source: 'Upper Blackrock Spire - Pyroguard Emberseer' },
        BACK: { itemId: 13340, name: 'Cape of the Black Baron', source: 'Stratholme - Baron Rivendare' },
        CHEST: { itemId: 11726, name: 'Savage Gladiator Chain', source: 'Blackrock Depths - Gorosh the Dervish' },
        WRISTS: { itemId: 12936, name: 'Battleborn Armbraces', source: 'Upper Blackrock Spire - Rend Blackhand' },
        HANDS: { itemId: 15063, name: 'Devilsaur Gauntlets', source: 'Leatherworking (250)' },
        WAIST: { itemId: 19137, name: 'Onslaught Girdle', source: 'Molten Core - Ragnaros' },
        LEGS: { itemId: 15062, name: 'Devilsaur Leggings', source: 'Leatherworking (250)' },
        FEET: { itemId: 14616, name: 'Bloodmail Boots', source: 'Scholomance - Bosses' },
        FINGER_1: { itemId: 17713, name: 'Blackstone Ring', source: 'Maraudon - Princess Theradras' },
        FINGER_2: { itemId: 19144, name: 'Band of Accuria', source: 'Molten Core - Ragnaros' },
        TRINKET_1: { itemId: 11815, name: 'Hand of Justice', source: 'Blackrock Depths - Emperor Dagran Thaurissan' },
        TRINKET_2: { itemId: 13965, name: 'Blackhand\'s Breadth', source: 'Upper Blackrock Spire Quest' },
        MAIN_HAND: { itemId: 17182, name: 'Sulfuras, Hand of Ragnaros', source: 'Molten Core - Ragnaros' },
        OFF_HAND: { itemId: 0, name: 'None (2H Weapon)', source: 'N/A' },
        RANGED: { itemId: 22397, name: 'Totem of Rage', source: 'World Drop' },
      },
    },
  },
  MAGE: {
    Frost: {
      phase: 1,
      slots: {
        HEAD: { itemId: 10504, name: 'Spellweaver\'s Turban', source: 'Upper Blackrock Spire - General Drakkisath' },
        NECK: { itemId: 17109, name: 'Choker of the Fire Lord', source: 'Molten Core - Ragnaros' },
        SHOULDERS: { itemId: 14112, name: 'Felcloth Shoulders', source: 'Tailoring (300)' },
        BACK: { itemId: 18208, name: 'Drape of Benediction', source: 'Dire Maul North' },
        CHEST: { itemId: 14152, name: 'Robe of the Archmage', source: 'Tailoring (300)' },
        WRISTS: { itemId: 16799, name: 'Arcanist Bindings', source: 'Molten Core - Trash Mobs' },
        HANDS: { itemId: 16801, name: 'Arcanist Gloves', source: 'Molten Core - Shazzrah' },
        WAIST: { itemId: 19131, name: 'Mana Igniting Cord', source: 'Molten Core - Magmadar' },
        LEGS: { itemId: 16796, name: 'Arcanist Leggings', source: 'Molten Core - Magmadar' },
        FEET: { itemId: 16800, name: 'Arcanist Boots', source: 'Molten Core - Lucifron' },
        FINGER_1: { itemId: 19145, name: 'Ring of Spell Power', source: 'Molten Core - Shazzrah' },
        FINGER_2: { itemId: 19145, name: 'Ring of Spell Power', source: 'Molten Core - Lucifron' },
        TRINKET_1: { itemId: 12930, name: 'Briarwood Reed', source: 'Upper Blackrock Spire - Jed Runewatcher' },
        TRINKET_2: { itemId: 18467, name: 'Royal Seal of Eldre\'Thalas', source: 'Dire Maul - Book Quest' },
        MAIN_HAND: { itemId: 17103, name: 'Azuresong Mageblade', source: 'Molten Core - Golemagg' },
        OFF_HAND: { itemId: 11904, name: 'Spirit of Aquementas', source: 'Quest - Linken\'s Adventure' },
        RANGED: { itemId: 13938, name: 'Bonecreeper Stylus', source: 'Scholomance - Darkmaster Gandling' },
      },
    },
    Fire: {
      phase: 1,
      slots: {
        HEAD: { itemId: 10504, name: 'Spellweaver\'s Turban', source: 'Upper Blackrock Spire - General Drakkisath' },
        NECK: { itemId: 17109, name: 'Choker of the Fire Lord', source: 'Molten Core - Ragnaros' },
        SHOULDERS: { itemId: 14112, name: 'Felcloth Shoulders', source: 'Tailoring (300)' },
        BACK: { itemId: 18208, name: 'Drape of Benediction', source: 'Dire Maul North' },
        CHEST: { itemId: 14152, name: 'Robe of the Archmage', source: 'Tailoring (300)' },
        WRISTS: { itemId: 16799, name: 'Arcanist Bindings', source: 'Molten Core - Trash Mobs' },
        HANDS: { itemId: 16801, name: 'Arcanist Gloves', source: 'Molten Core - Shazzrah' },
        WAIST: { itemId: 19131, name: 'Mana Igniting Cord', source: 'Molten Core - Magmadar' },
        LEGS: { itemId: 16796, name: 'Arcanist Leggings', source: 'Molten Core - Magmadar' },
        FEET: { itemId: 16800, name: 'Arcanist Boots', source: 'Molten Core - Lucifron' },
        FINGER_1: { itemId: 19145, name: 'Ring of Spell Power', source: 'Molten Core - Shazzrah' },
        FINGER_2: { itemId: 19145, name: 'Ring of Spell Power', source: 'Molten Core - Lucifron' },
        TRINKET_1: { itemId: 12930, name: 'Briarwood Reed', source: 'Upper Blackrock Spire - Jed Runewatcher' },
        TRINKET_2: { itemId: 18467, name: 'Royal Seal of Eldre\'Thalas', source: 'Dire Maul - Book Quest' },
        MAIN_HAND: { itemId: 17103, name: 'Azuresong Mageblade', source: 'Molten Core - Golemagg' },
        OFF_HAND: { itemId: 11904, name: 'Spirit of Aquementas', source: 'Quest - Linken\'s Adventure' },
        RANGED: { itemId: 13938, name: 'Bonecreeper Stylus', source: 'Scholomance - Darkmaster Gandling' },
      },
    },
    Arcane: {
      phase: 1,
      slots: {
        HEAD: { itemId: 10504, name: 'Spellweaver\'s Turban', source: 'Upper Blackrock Spire - General Drakkisath' },
        NECK: { itemId: 17109, name: 'Choker of the Fire Lord', source: 'Molten Core - Ragnaros' },
        SHOULDERS: { itemId: 16797, name: 'Arcanist Mantle', source: 'Molten Core - Baron Geddon' },
        BACK: { itemId: 18208, name: 'Drape of Benediction', source: 'Dire Maul North' },
        CHEST: { itemId: 14152, name: 'Robe of the Archmage', source: 'Tailoring (300)' },
        WRISTS: { itemId: 16799, name: 'Arcanist Bindings', source: 'Molten Core - Trash Mobs' },
        HANDS: { itemId: 16801, name: 'Arcanist Gloves', source: 'Molten Core - Shazzrah' },
        WAIST: { itemId: 19131, name: 'Mana Igniting Cord', source: 'Molten Core - Magmadar' },
        LEGS: { itemId: 16796, name: 'Arcanist Leggings', source: 'Molten Core - Magmadar' },
        FEET: { itemId: 16800, name: 'Arcanist Boots', source: 'Molten Core - Lucifron' },
        FINGER_1: { itemId: 19145, name: 'Ring of Spell Power', source: 'Molten Core - Shazzrah' },
        FINGER_2: { itemId: 19145, name: 'Ring of Spell Power', source: 'Molten Core - Lucifron' },
        TRINKET_1: { itemId: 12930, name: 'Briarwood Reed', source: 'Upper Blackrock Spire - Jed Runewatcher' },
        TRINKET_2: { itemId: 18467, name: 'Royal Seal of Eldre\'Thalas', source: 'Dire Maul - Book Quest' },
        MAIN_HAND: { itemId: 17103, name: 'Azuresong Mageblade', source: 'Molten Core - Golemagg' },
        OFF_HAND: { itemId: 11904, name: 'Spirit of Aquementas', source: 'Quest - Linken\'s Adventure' },
        RANGED: { itemId: 13938, name: 'Bonecreeper Stylus', source: 'Scholomance - Darkmaster Gandling' },
      },
    },
  },
  WARLOCK: {
    Destruction: {
      phase: 1,
      slots: {
        HEAD: { itemId: 10504, name: 'Spellweaver\'s Turban', source: 'Upper Blackrock Spire - General Drakkisath' },
        NECK: { itemId: 17109, name: 'Choker of the Fire Lord', source: 'Molten Core - Ragnaros' },
        SHOULDERS: { itemId: 14112, name: 'Felcloth Shoulders', source: 'Tailoring (300)' },
        BACK: { itemId: 18208, name: 'Drape of Benediction', source: 'Dire Maul North' },
        CHEST: { itemId: 14136, name: 'Robes of the Void', source: 'Tailoring (300)' },
        WRISTS: { itemId: 16804, name: 'Felheart Bracers', source: 'Molten Core - Trash Mobs' },
        HANDS: { itemId: 14146, name: 'Felcloth Gloves', source: 'Tailoring (300)' },
        WAIST: { itemId: 19131, name: 'Mana Igniting Cord', source: 'Molten Core - Magmadar' },
        LEGS: { itemId: 16810, name: 'Felheart Pants', source: 'Molten Core - Magmadar' },
        FEET: { itemId: 16805, name: 'Felheart Slippers', source: 'Molten Core - Lucifron' },
        FINGER_1: { itemId: 19145, name: 'Ring of Spell Power', source: 'Molten Core - Shazzrah' },
        FINGER_2: { itemId: 19145, name: 'Ring of Spell Power', source: 'Molten Core - Lucifron' },
        TRINKET_1: { itemId: 12930, name: 'Briarwood Reed', source: 'Upper Blackrock Spire - Jed Runewatcher' },
        TRINKET_2: { itemId: 18468, name: 'Royal Seal of Eldre\'Thalas', source: 'Dire Maul - Book Quest' },
        MAIN_HAND: { itemId: 17103, name: 'Azuresong Mageblade', source: 'Molten Core - Golemagg' },
        OFF_HAND: { itemId: 11904, name: 'Spirit of Aquementas', source: 'Quest - Linken\'s Adventure' },
        RANGED: { itemId: 13938, name: 'Bonecreeper Stylus', source: 'Scholomance - Darkmaster Gandling' },
      },
    },
    Affliction: {
      phase: 1,
      slots: {
        HEAD: { itemId: 10504, name: 'Spellweaver\'s Turban', source: 'Upper Blackrock Spire - General Drakkisath' },
        NECK: { itemId: 17109, name: 'Choker of the Fire Lord', source: 'Molten Core - Ragnaros' },
        SHOULDERS: { itemId: 14112, name: 'Felcloth Shoulders', source: 'Tailoring (300)' },
        BACK: { itemId: 18208, name: 'Drape of Benediction', source: 'Dire Maul North' },
        CHEST: { itemId: 14136, name: 'Robes of the Void', source: 'Tailoring (300)' },
        WRISTS: { itemId: 16804, name: 'Felheart Bracers', source: 'Molten Core - Trash Mobs' },
        HANDS: { itemId: 14146, name: 'Felcloth Gloves', source: 'Tailoring (300)' },
        WAIST: { itemId: 19131, name: 'Mana Igniting Cord', source: 'Molten Core - Magmadar' },
        LEGS: { itemId: 14142, name: 'Felcloth Pants', source: 'Tailoring (300)' },
        FEET: { itemId: 16805, name: 'Felheart Slippers', source: 'Molten Core - Lucifron' },
        FINGER_1: { itemId: 19145, name: 'Ring of Spell Power', source: 'Molten Core - Shazzrah' },
        FINGER_2: { itemId: 19145, name: 'Ring of Spell Power', source: 'Molten Core - Lucifron' },
        TRINKET_1: { itemId: 12930, name: 'Briarwood Reed', source: 'Upper Blackrock Spire - Jed Runewatcher' },
        TRINKET_2: { itemId: 18468, name: 'Royal Seal of Eldre\'Thalas', source: 'Dire Maul - Book Quest' },
        MAIN_HAND: { itemId: 17103, name: 'Azuresong Mageblade', source: 'Molten Core - Golemagg' },
        OFF_HAND: { itemId: 11904, name: 'Spirit of Aquementas', source: 'Quest - Linken\'s Adventure' },
        RANGED: { itemId: 13938, name: 'Bonecreeper Stylus', source: 'Scholomance - Darkmaster Gandling' },
      },
    },
    Demonology: {
      phase: 1,
      slots: {
        HEAD: { itemId: 10504, name: 'Spellweaver\'s Turban', source: 'Upper Blackrock Spire - General Drakkisath' },
        NECK: { itemId: 17109, name: 'Choker of the Fire Lord', source: 'Molten Core - Ragnaros' },
        SHOULDERS: { itemId: 16807, name: 'Felheart Shoulder Pads', source: 'Molten Core - Baron Geddon' },
        BACK: { itemId: 18208, name: 'Drape of Benediction', source: 'Dire Maul North' },
        CHEST: { itemId: 14136, name: 'Robes of the Void', source: 'Tailoring (300)' },
        WRISTS: { itemId: 16804, name: 'Felheart Bracers', source: 'Molten Core - Trash Mobs' },
        HANDS: { itemId: 14146, name: 'Felcloth Gloves', source: 'Tailoring (300)' },
        WAIST: { itemId: 19131, name: 'Mana Igniting Cord', source: 'Molten Core - Magmadar' },
        LEGS: { itemId: 16810, name: 'Felheart Pants', source: 'Molten Core - Magmadar' },
        FEET: { itemId: 16805, name: 'Felheart Slippers', source: 'Molten Core - Lucifron' },
        FINGER_1: { itemId: 19145, name: 'Ring of Spell Power', source: 'Molten Core - Shazzrah' },
        FINGER_2: { itemId: 19145, name: 'Ring of Spell Power', source: 'Molten Core - Lucifron' },
        TRINKET_1: { itemId: 12930, name: 'Briarwood Reed', source: 'Upper Blackrock Spire - Jed Runewatcher' },
        TRINKET_2: { itemId: 18468, name: 'Royal Seal of Eldre\'Thalas', source: 'Dire Maul - Book Quest' },
        MAIN_HAND: { itemId: 17103, name: 'Azuresong Mageblade', source: 'Molten Core - Golemagg' },
        OFF_HAND: { itemId: 11904, name: 'Spirit of Aquementas', source: 'Quest - Linken\'s Adventure' },
        RANGED: { itemId: 13938, name: 'Bonecreeper Stylus', source: 'Scholomance - Darkmaster Gandling' },
      },
    },
  },
  DRUID: {
    'Feral DPS': {
      phase: 1,
      slots: {
        HEAD: { itemId: 8345, name: 'Wolfshead Helm', source: 'Leatherworking (225)' },
        NECK: { itemId: 18404, name: 'Onyxia Tooth Pendant', source: "Onyxia's Lair - Head of Onyxia" },
        SHOULDERS: { itemId: 13405, name: 'Truestrike Shoulders', source: 'Upper Blackrock Spire - Pyroguard Emberseer' },
        BACK: { itemId: 13340, name: 'Cape of the Black Baron', source: 'Stratholme - Baron Rivendare' },
        CHEST: { itemId: 12895, name: 'Breastplate of Bloodthirst', source: 'Blacksmithing (300)' },
        WRISTS: { itemId: 12936, name: 'Battleborn Armbraces', source: 'Upper Blackrock Spire - Rend Blackhand' },
        HANDS: { itemId: 15063, name: 'Devilsaur Gauntlets', source: 'Leatherworking (250)' },
        WAIST: { itemId: 13959, name: 'Cloudrunner Girdle', source: 'Lower Blackrock Spire - Quartermaster Zigris' },
        LEGS: { itemId: 15062, name: 'Devilsaur Leggings', source: 'Leatherworking (250)' },
        FEET: { itemId: 14616, name: 'Bloodmail Boots', source: 'Scholomance - Bosses' },
        FINGER_1: { itemId: 19144, name: 'Band of Accuria', source: 'Molten Core - Ragnaros' },
        FINGER_2: { itemId: 17713, name: 'Blackstone Ring', source: 'Maraudon - Princess Theradras' },
        TRINKET_1: { itemId: 11815, name: 'Hand of Justice', source: 'Blackrock Depths - Emperor Dagran Thaurissan' },
        TRINKET_2: { itemId: 13965, name: 'Blackhand\'s Breadth', source: 'Upper Blackrock Spire Quest' },
        MAIN_HAND: { itemId: 9449, name: 'Manual Crowd Pummeler', source: 'Gnomeregan - Crowd Pummeler 9-60' },
        OFF_HAND: { itemId: 0, name: 'None (2H Weapon)', source: 'N/A' },
        RANGED: { itemId: 22398, name: 'Idol of Ferocity', source: 'World Drop' },
      },
    },
    'Feral Tank': {
      phase: 1,
      slots: {
        HEAD: { itemId: 16834, name: 'Cenarion Helm', source: 'Molten Core - Garr' },
        NECK: { itemId: 17064, name: 'Medallion of Steadfast Might', source: 'Molten Core - Magmadar' },
        SHOULDERS: { itemId: 16836, name: 'Cenarion Spaulders', source: 'Molten Core - Baron Geddon' },
        BACK: { itemId: 19084, name: 'Dragon\'s Blood Cape', source: 'Molten Core - Ragnaros' },
        CHEST: { itemId: 12895, name: 'Breastplate of Bloodthirst', source: 'Blacksmithing (300)' },
        WRISTS: { itemId: 16831, name: 'Cenarion Bracers', source: 'Molten Core - Trash Mobs' },
        HANDS: { itemId: 16828, name: 'Cenarion Gloves', source: 'Molten Core - Gehennas' },
        WAIST: { itemId: 16829, name: 'Cenarion Belt', source: 'Molten Core - Trash Mobs' },
        LEGS: { itemId: 16835, name: 'Cenarion Leggings', source: 'Molten Core - Magmadar' },
        FEET: { itemId: 16830, name: 'Cenarion Boots', source: 'Molten Core - Lucifron' },
        FINGER_1: { itemId: 19147, name: 'Ring of Binding', source: 'Molten Core - Baron Geddon' },
        FINGER_2: { itemId: 17713, name: 'Blackstone Ring', source: 'Maraudon - Princess Theradras' },
        TRINKET_1: { itemId: 11815, name: 'Hand of Justice', source: 'Blackrock Depths - Emperor Dagran Thaurissan' },
        TRINKET_2: { itemId: 19406, name: 'Drake Fang Talisman', source: 'Blackwing Lair - Ebonroc' },
        MAIN_HAND: { itemId: 18842, name: 'Staff of Dominance', source: 'Molten Core - Golemagg' },
        OFF_HAND: { itemId: 0, name: 'None (Staff)', source: 'N/A' },
        RANGED: { itemId: 22399, name: 'Idol of Brutality', source: 'World Drop' },
      },
    },
    Restoration: {
      phase: 1,
      slots: {
        HEAD: { itemId: 16834, name: 'Cenarion Helm', source: 'Molten Core - Garr' },
        NECK: { itemId: 17109, name: 'Choker of the Fire Lord', source: 'Molten Core - Ragnaros' },
        SHOULDERS: { itemId: 16836, name: 'Cenarion Spaulders', source: 'Molten Core - Baron Geddon' },
        BACK: { itemId: 18510, name: 'Hide of the Wild', source: 'Leatherworking (300)' },
        CHEST: { itemId: 13346, name: 'Robes of the Exalted', source: 'Stratholme - Baron Rivendare' },
        WRISTS: { itemId: 16831, name: 'Cenarion Bracers', source: 'Molten Core - Trash Mobs' },
        HANDS: { itemId: 16828, name: 'Cenarion Gloves', source: 'Molten Core - Gehennas' },
        WAIST: { itemId: 16829, name: 'Cenarion Belt', source: 'Molten Core - Trash Mobs' },
        LEGS: { itemId: 16835, name: 'Cenarion Leggings', source: 'Molten Core - Magmadar' },
        FEET: { itemId: 16830, name: 'Cenarion Boots', source: 'Molten Core - Lucifron' },
        FINGER_1: { itemId: 19140, name: 'Cauterizing Band', source: 'Molten Core - Majordomo Executus' },
        FINGER_2: { itemId: 16058, name: 'Fordring\'s Seal', source: 'Quest - In Dreams' },
        TRINKET_1: { itemId: 18472, name: 'Royal Seal of Eldre\'Thalas', source: 'Dire Maul - Book Quest' },
        TRINKET_2: { itemId: 12930, name: 'Briarwood Reed', source: 'Upper Blackrock Spire - Jed Runewatcher' },
        MAIN_HAND: { itemId: 17105, name: 'Aurastone Hammer', source: 'Molten Core - Garr' },
        OFF_HAND: { itemId: 11904, name: 'Spirit of Aquementas', source: 'Quest - Linken\'s Adventure' },
        RANGED: { itemId: 22400, name: 'Idol of Rejuvenation', source: 'World Drop' },
      },
    },
    Balance: {
      phase: 1,
      slots: {
        HEAD: { itemId: 10504, name: 'Spellweaver\'s Turban', source: 'Upper Blackrock Spire - General Drakkisath' },
        NECK: { itemId: 17109, name: 'Choker of the Fire Lord', source: 'Molten Core - Ragnaros' },
        SHOULDERS: { itemId: 16836, name: 'Cenarion Spaulders', source: 'Molten Core - Baron Geddon' },
        BACK: { itemId: 18208, name: 'Drape of Benediction', source: 'Dire Maul North' },
        CHEST: { itemId: 14136, name: 'Robes of the Void', source: 'Tailoring (300)' },
        WRISTS: { itemId: 16831, name: 'Cenarion Bracers', source: 'Molten Core - Trash Mobs' },
        HANDS: { itemId: 16828, name: 'Cenarion Gloves', source: 'Molten Core - Gehennas' },
        WAIST: { itemId: 19131, name: 'Mana Igniting Cord', source: 'Molten Core - Magmadar' },
        LEGS: { itemId: 16835, name: 'Cenarion Leggings', source: 'Molten Core - Magmadar' },
        FEET: { itemId: 16830, name: 'Cenarion Boots', source: 'Molten Core - Lucifron' },
        FINGER_1: { itemId: 19145, name: 'Ring of Spell Power', source: 'Molten Core - Shazzrah' },
        FINGER_2: { itemId: 19145, name: 'Ring of Spell Power', source: 'Molten Core - Lucifron' },
        TRINKET_1: { itemId: 12930, name: 'Briarwood Reed', source: 'Upper Blackrock Spire - Jed Runewatcher' },
        TRINKET_2: { itemId: 18472, name: 'Royal Seal of Eldre\'Thalas', source: 'Dire Maul - Book Quest' },
        MAIN_HAND: { itemId: 17103, name: 'Azuresong Mageblade', source: 'Molten Core - Golemagg' },
        OFF_HAND: { itemId: 11904, name: 'Spirit of Aquementas', source: 'Quest - Linken\'s Adventure' },
        RANGED: { itemId: 22399, name: 'Idol of the Moon', source: 'World Drop' },
      },
    },
  },
};
